name: GitHub Actions Demo
on: [push]
jobs:
  Check-Docker-Python-Versions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Checking Docker and Python version"
      - run: docker --version
      - run: python --version
      - name: Check Docker & Python versions
        uses: actions/checkout@v3
