name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Versions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Checking Docker and Python version"
      - name: Check out repository code
        uses: actions/checkout@v3
